name: Build

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      id: go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Check out code
      uses: actions/checkout@v2

    - name: Test
      run: go test -v ./pkg/... ./test/...

    - name: Build
      run: ./scripts/build.sh
      shell: bash

    - name: Save artifacts
      uses: actions/upload-artifact@v2
      with:
        name: binaries
        path: bin/out/

    - name: Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./bin/docker/build
        file: ./scripts/Dockerfile
        platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
        push: true
        tags: "evocloud/spf:latest"
