name: Release

on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      id: go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Build
      run: ./scripts/build.sh
      shell: bash

    - name: Release
      run: |
        set -x
        assets=()
        for asset in bin/out/*.tar.gz bin/out/*.txt; do
          assets+=("-a" "$asset")
        done
        tag_name="${GITHUB_REF##*/}"
        hub release create "${assets[@]}" -m "$tag_name" "$tag_name"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}    
